### PR TITLE
[REVIEW] Like posts with Id

### PR DESCRIPTION
**Pull request by onurakpolat**
This adds the ability to like a post with a valid postId only.

### CODE REVIEW

**Comment by onurakpolat** [comment]
@nilsen340 please review

**Comment by xla** [comment]
@onurakpolat This change only includes the test code, is the implementation not part of the PR?

Additionally could you describe a scenario where only the id of a Post is present when doing an interaction like a like?

**Comment by onurakpolat** [comment]
@xla I just the implementation. The scenario is whenever a client decides to use their own data structure for the representation in the UI.

**Comment by nilsen340** [comment]
@onurakpolat we should also provide unlike with postId if we provide like with postId.

**Comment by onurakpolat** [comment]
@nilsen340 done.

**Comment by nilsen340** [comment]
👍

**Comment by xla** [comment]
👍 :shipit: :octocat: 🍡

**Pull request merged**
