### PR TITLE
Add metadata to user object

### PR DESCRIPTION
**Pull request by nilsen340**

### CODE REVIEW

**Comment by xla** [comment]
@nilsen340 Success. Is there a way to limit the number of keys somebody can store?

**Comment by nilsen340** [comment]
@xla does the api not do this already? if the API returns a error message we would return that as a error event to the client.

**Comment by xla** [comment]
@nilsen340 Reasonable, let me prepare something.

**Comment by xla** [comment]
Until then 👍  :shipit: :octocat: 🍡

**Comment by onurakpolat** [comment]
👍

**Pull request merged**
